spring:
 application:
  name: EXTERNAL-CONFIG-SERVER

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9904/eureka/
  instance:
    hostname: localhost 
