spring:
 application:
    name: USER-SERVICE

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9904/eureka/
  instance:
    hostname: localhost 
